export const ADD_STRING = 'ADD_STRING';
export const STRING_LOADING = 'STRING_LOADING';
export const STRING_FAILED = 'STRING_FAILED';


export const ADD_PROFILE = 'ADD_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const GET_PROFILE = 'GET_PROFILE';
